controller_list:
  - name: panda_arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - joint_arm_1
      - joint_arm_2
      - joint_arm_3
      - joint_arm_4
      - joint_arm_5
      - joint_arm_6
      - joint_arm_7

  # - name: panda_hand_controller
  #   action_ns: follow_joint_trajectory
  #   type: FollowJointTrajectory
  #   default: true
  #   joints:
  #     - joint_finger_l
  #     - joint_finger_r

  # - name: panda_hand_controller
  #   action_ns: gripper_cmd
  #   type: GripperCommand
  #   default: true
  #   parallel: true
  #   joints:
  #     - joint_finger_l
  #     - joint_finger_r
