controller_list:
  - name: fake_panda_arm_controller
    joints:
      - joint_arm_1
      - joint_arm_2
      - joint_arm_3
      - joint_arm_4
      - joint_arm_5
      - joint_arm_6
      - joint_arm_7
  - name: fake_panda_hand_controller
    joints:
      - joint_finger_l