# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  joint_arm_1:
    has_velocity_limits: true
    max_velocity: 2.3925
    has_acceleration_limits: false
    max_acceleration: 0
  joint_arm_2:
    has_velocity_limits: true
    max_velocity: 2.3925
    has_acceleration_limits: false
    max_acceleration: 0
  joint_arm_3:
    has_velocity_limits: true
    max_velocity: 2.3925
    has_acceleration_limits: false
    max_acceleration: 0
  joint_arm_4:
    has_velocity_limits: true
    max_velocity: 2.3925
    has_acceleration_limits: false
    max_acceleration: 0
  joint_arm_5:
    has_velocity_limits: true
    max_velocity: 2.871
    has_acceleration_limits: false
    max_acceleration: 0
  joint_arm_6:
    has_velocity_limits: true
    max_velocity: 2.871
    has_acceleration_limits: false
    max_acceleration: 0
  joint_arm_7:
    has_velocity_limits: true
    max_velocity: 2.871
    has_acceleration_limits: false
    max_acceleration: 0
  joint_finger_l:
    has_velocity_limits: true
    max_velocity: 0.2
    has_acceleration_limits: false
    max_acceleration: 0
  joint_finger_r:
    has_velocity_limits: true
    max_velocity: 0.2
    has_acceleration_limits: false
    max_acceleration: 0