sensors:
  - sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
    point_cloud_topic: /xtion_sensor/depth/points
    max_range: 10.0
    padding_offset: 0.01
    padding_scale: 1.0
    point_subsample: 0.01
    filtered_cloud_topic: output_cloud
