panda_arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - joint_arm_1
    - joint_arm_2
    - joint_arm_3
    - joint_arm_4
    - joint_arm_5
    - joint_arm_6
    - joint_arm_7

panda_hand_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - joint_finger_l
    - joint_finger_r
