gazebo_ros_control:
  pid_gains:
    joint_arm_1:
      p: 1000.0
      i: 0.0
      d: 0.1
      i_clamp: 0.0
      antiwindup: false
      publish_state: true
    joint_arm_2:
      p: 1000.0
      i: 0.0
      d: 0.1
      i_clamp: 0.0
      antiwindup: false
      publish_state: true
    joint_arm_3:
      p: 1000.0
      i: 0.0
      d: 0.1
      i_clamp: 0.0
      antiwindup: false
      publish_state: true
    joint_arm_4:
      p: 1000.0
      i: 0.0
      d: 0.1
      i_clamp: 0.0
      antiwindup: false
      publish_state: true
    joint_arm_5:
      p: 1000.0
      i: 0.0
      d: 0.1
      i_clamp: 0.0
      antiwindup: false
      publish_state: true
    joint_arm_6:
      p: 1000.0
      i: 0.0
      d: 0.1
      i_clamp: 0.0
      antiwindup: false
      publish_state: true
    joint_arm_7:
      p: 1000.0
      i: 0.0
      d: 0.1
      i_clamp: 0.0
      antiwindup: false
      publish_state: true
